apiVersion: v1
kind: ConfigMap
metadata:
  name: fit-and-fails-config
  namespace: fit-and-fails
data:
  PORT: "4000"
  WATER_DEFAULT_GOAL: "2000"
  FRONTEND_URL: "https://fitandfails.example.com"
  VITE_API_URL: "https://fitandfails.example.com"
