apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit-and-fails-frontend
  namespace: fit-and-fails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fit-and-fails-frontend
  template:
    metadata:
      labels:
        app: fit-and-fails-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/elieltondevopsengineer/fit-and-fails-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: fit-and-fails-config
                  key: VITE_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: fit-and-fails-frontend
  namespace: fit-and-fails
spec:
  type: LoadBalancer
  selector:
    app: fit-and-fails-frontend
  ports:
    - port: 80
      targetPort: 80
