apiVersion: v1
kind: Secret
metadata:
  name: fit-and-fails-secrets
  namespace: fit-and-fails
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXRfand0
  DATABASE_URL: cG9zdGdyZXM6Ly9maXQtYW5kLWZhaWxzOnN1cGVyc2VjcmV0QGZpdC1hbmQtZmFpbHMtcG9zdGdyZXM6NTQzMi9maXRhbmRmYWlscw==
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=
